name: poly
description: A library for checking if given point(s) is present inside Polygon or not.
version: 2.0.1
homepage: https://github.com/Sacchid/poly
author: sacchi <22224760+Sacchid@users.noreply.github.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  csv: ^5.0.0
  collection: ^1.14.11

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
